<h1>Determining Who on the Titanic would have Survived Based on Age, Sex, and Class </h1>

Ben Douglass

12/6/16

Big Data, Period 8

<h3> 1. Average accuracy of three types of Machine Learning Algorithms: DecisionTree, KNeighbors, and RandomForest

In [1]:
#code to import a csv and convert it to a numpy array
#import the numpy library
import numpy as np
#open the file
raw_data = open("titanic.csv")
raw_data1 = open("titanic_no1.csv")
raw_data2 = open("titanic_no2.csv")
#load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
dataset1 = np.loadtxt(raw_data1, delimiter=",")
dataset2 = np.loadtxt(raw_data2, delimiter=",")
#'shape' is the dimensions of the matrix
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:3]
y = dataset[:,3]
print(X)
print(y)


(2201, 4)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 ..., 
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]


In [2]:
#My first try. I had some kind of issue that caused my scores to not be nearly high enough, so I tried another method.

from sklearn import datasets
import random
import statistics


from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)

from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
(accuracy_score(tree_predictions, y_test))

for ii in range (10):
    print (tree_predictions[ii])

print ("Average:", ((tree_predictions[0] ++ tree_predictions[1] ++ tree_predictions[2] ++ tree_predictions[3] ++ tree_predictions[4] ++ tree_predictions[5] ++ tree_predictions[6] ++ tree_predictions[7] ++ tree_predictions[8] ++ tree_predictions[9])/10))


print (" ")

from sklearn import neighbors
knn_classifier = neighbors.KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, y_train)
knn_predictions = knn_classifier.predict(X_test)

print(accuracy_score(knn_predictions, y_test))

for ii in range (10):
    print (knn_predictions[ii])

print ("Average:", ((knn_predictions[0] ++ knn_predictions[1] ++ knn_predictions[2] ++ knn_predictions[3] ++ knn_predictions[4] ++ knn_predictions[5] ++ knn_predictions[6] ++ knn_predictions[7] ++ knn_predictions[8] ++ knn_predictions[9])/10))


print (" ")

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print (accuracy_score(rf_predictions, y_test))


for ii in range (10):
    print (rf_predictions[ii])

print ("Average:", ((rf_predictions[0] ++ rf_predictions[1] ++ rf_predictions[2] ++ rf_predictions[3] ++ rf_predictions[4] ++ rf_predictions[5] ++ rf_predictions[6] ++ rf_predictions[7] ++ rf_predictions[8] ++ rf_predictions[9])/10))

print(statistics.mean(knn_predictions))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
Average: 0.0
 
0.780199818347
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
Average: 0.0
 
0.780199818347
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
Average: 0.0
0.128065395095


In [3]:
#Doc: Help from James
#This is what I used to answer Question 1

counter = 0 
list_one = []
list_two = []
list_three = []

while counter < 10:
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
    
    from sklearn import tree
    tree_classifier = tree.DecisionTreeClassifier();
    tree_classifier = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier.predict(X_test)

    from sklearn.metrics import accuracy_score
    data = (accuracy_score(tree_predictions, y_test))
    list_one.append(data);
    
    
    from sklearn import neighbors
    knn_classifier = neighbors.KNeighborsClassifier()
    knn_classifier = knn_classifier.fit(X_train, y_train)
    knn_predictions = knn_classifier.predict(X_test)

    data2 = (accuracy_score(knn_predictions, y_test))
    list_two.append(data2);
    
    
    from sklearn import ensemble
    rf_classifier = ensemble.RandomForestClassifier()
    rf_classifier = rf_classifier.fit(X_train, y_train)
    rf_predictions = rf_classifier.predict(X_test)

    data3 = (accuracy_score(rf_predictions, y_test))
    list_three.append(data3)
    
    counter+=1
    
print(list_one)
print("Average Accuracy of DecisionTree:", statistics.mean(list_one))
print ( )
print(list_two)
print("Average Accuracy of KNeighbors", statistics.mean(list_two))
print ( )
print(list_three)
print("Average Accuracy of RandomForest", statistics.mean(list_three))

    
    
    

[0.78019981834695729, 0.77111716621253401, 0.76930063578564944, 0.79382379654859214, 0.76748410535876477, 0.78564940962761132, 0.7756584922797457, 0.79927338782924617, 0.78474114441416898, 0.78019981834695729]
Average Accuracy of DecisionTree: 0.780744777475

[0.77838328792007261, 0.57765667574931878, 0.56130790190735691, 0.77838328792007261, 0.78201634877384196, 0.77202543142597635, 0.78837420526793822, 0.79291553133514991, 0.75930971843778383, 0.79473206176203448]
Average Accuracy of KNeighbors 0.73851044505

[0.78019981834695729, 0.77111716621253401, 0.76930063578564944, 0.79382379654859214, 0.76748410535876477, 0.7756584922797457, 0.78837420526793822, 0.79654859218891916, 0.78474114441416898, 0.78019981834695729]
Average Accuracy of RandomForest 0.780744777475


<h3>Question 1 Answer: </h3>

I found that the third algorithm, <b>RandomForest</b>, was the most accurate because it has the highest accuracy score of 78.8. However, the other two machine learning algorithms were close behind, with scores of 78.6 from DecisionTree and 77.0 from KNeighbors. 


<h3> 2. Using the most accurate algorithm, determine whether the following people would have survived:


an adult male in 3rd class, an adult female in 1st class, and a female child in 1st class

In [116]:
from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)

print("0 = dead")
print("1 = alive")


rf_predictions = rf_classifier.predict([[3, 1, 1]])
print (rf_predictions)

rf_predictions = rf_classifier.predict([[1, 1, 0]])
print (rf_predictions)

rf_predictions = rf_classifier.predict([[1, 0, 0]])
print (rf_predictions)

0 = dead
1 = alive
[ 0.]
[ 1.]
[ 1.]


<h3>Question 2 Answer: </h3>

I used the RandomForest algorithm, which I found in the previous question was the most accurate. 

<u>Here is who lived and who died:</u>

The adult male in 3rd class most likely <b>died</b>

The adult female in 1st class most likely <b>lived</b>

the female child in 1st class most likely <b>lived</b>


<h3> 3. Which is the most important feature: Age, Class, or Gender?

In [4]:
#I initially tried to create different excell files with one feature removed and see what the accuracy scores were.
#However, this method didn't work because for some reason the accuracy scores did not change very much. 
#So I did a different method. 

X = dataset1[:,0:2]
y = dataset1[:,2]
print(X)
print(y)

counter = 0 
list_one = []
list_two = []
list_three = []

while counter < 10:
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
    
    from sklearn import tree
    tree_classifier = tree.DecisionTreeClassifier();
    tree_classifier = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier.predict(X_test)

    from sklearn.metrics import accuracy_score
    data = (accuracy_score(tree_predictions, y_test))
    list_one.append(data);
    
    
    from sklearn import neighbors
    knn_classifier = neighbors.KNeighborsClassifier()
    knn_classifier = knn_classifier.fit(X_train, y_train)
    knn_predictions = knn_classifier.predict(X_test)

    data2 = (accuracy_score(knn_predictions, y_test))
    list_two.append(data2);
    
    
    from sklearn import ensemble
    rf_classifier = ensemble.RandomForestClassifier()
    rf_classifier = rf_classifier.fit(X_train, y_train)
    rf_predictions = rf_classifier.predict(X_test)

    data3 = (accuracy_score(rf_predictions, y_test))
    list_three.append(data3)
    
    counter = counter +1
    
print(list_one)
print("Average Accuracy of DecisionTree:", statistics.mean(list_one))
print ( )
print(list_two)
print("Average Accuracy of KNeighbors", statistics.mean(list_two))
print ( )
print(list_three)
print("Average Accuracy of RandomForest", statistics.mean(list_three))

    
    
    

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]
[0.76839237057220711, 0.77656675749318804, 0.78110808356039962, 0.76203451407811085, 0.76475930971843775, 0.76930063578564944, 0.76657584014532243, 0.78019981834695729, 0.75567665758401448, 0.76839237057220711]
Average Accuracy of DecisionTree: 0.769300635786

[0.76657584014532243, 0.77202543142597635, 0.77747502270663038, 0.77838328792007261, 0.77656675749318804, 0.77293369663941869, 0.76657584014532243, 0.78019981834695729, 0.74750227066303365, 0.77929155313351495]
Average Accuracy of KNeighbors 0.771752951862

[0.76839237057220711, 0.77656675749318804, 0.78110808356039962, 0.76839237057220711, 0.76021798365122617, 0.76930063578564944, 0.76657584014532243, 0.78019981834695729, 0.75567665758401448, 0.76839237057220711]
Average Accuracy of RandomForest 0.769482288828


In [5]:
X = dataset2[:,0:2]
y = dataset2[:,2]
print(X)
print(y)

counter = 0 
list_one = []
list_two = []
list_three = []

while counter < 10:
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .5)
    
    from sklearn import tree
    tree_classifier = tree.DecisionTreeClassifier();
    tree_classifier = tree_classifier.fit(X_train, y_train)
    tree_predictions = tree_classifier.predict(X_test)

    from sklearn.metrics import accuracy_score
    data = (accuracy_score(tree_predictions, y_test))
    list_one.append(data);
    
    
    from sklearn import neighbors
    knn_classifier = neighbors.KNeighborsClassifier()
    knn_classifier = knn_classifier.fit(X_train, y_train)
    knn_predictions = knn_classifier.predict(X_test)

    data2 = (accuracy_score(knn_predictions, y_test))
    list_two.append(data2);
    
    
    from sklearn import ensemble
    rf_classifier = ensemble.RandomForestClassifier()
    rf_classifier = rf_classifier.fit(X_train, y_train)
    rf_predictions = rf_classifier.predict(X_test)

    data3 = (accuracy_score(rf_predictions, y_test))
    list_three.append(data3)
    
    counter = counter +1
    
print(list_one)
print("Average Accuracy of DecisionTree:", statistics.mean(list_one))
print ( )
print(list_two)
print("Average Accuracy of KNeighbors", statistics.mean(list_two))
print ( )
print(list_three)
print("Average Accuracy of RandomForest", statistics.mean(list_three))

    
    
    

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 ..., 
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]
[0.78383287920072664, 0.77202543142597635, 0.77384196185286103, 0.76203451407811085, 0.78564940962761132, 0.79564032697547682, 0.76385104450499541, 0.78564940962761132, 0.78928247048138056, 0.76475930971843775]
Average Accuracy of DecisionTree: 0.777656675749

[0.78383287920072664, 0.56494096276112626, 0.77384196185286103, 0.74114441416893728, 0.56494096276112626, 0.79564032697547682, 0.78383287920072664, 0.77384196185286103, 0.78928247048138056, 0.75386012715712991]
Average Accuracy of KNeighbors 0.732515894641

[0.78383287920072664, 0.77202543142597635, 0.77384196185286103, 0.76203451407811085, 0.78564940962761132, 0.78474114441416898, 0.76385104450499541, 0.78564940962761132, 0.78928247048138056, 0.76475930971843775]
Average Accuracy of RandomForest 0.776566757493


In [ ]:
#DOC: Andrew
#Here is the method I used.

import random
import numpy as np
import sys
import time
import threading
from sklearn import ensemble
from sklearn import neighbors
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.cross_validation import train_test_split
from math import sqrt

raw_data = open("titanic.csv");
dataset = np.loadtxt(raw_data, delimiter=",");

X = dataset[:,0:3];
y = dataset[:,3];

def neednum():
    mmn = input("Please enter a number between 0 and 3: ");
    try:
        cnum = int(mmn);
        Class = cnum;
        if cnum > 3:
            neednum();
        return Class;
    except:
        neednum();

Class = input("What class are you? (0-3, 0 being crew, 3 being third): ");
cnum = 0;
try:
    cnum = int(Class);
except:
    neednum();
if cnum > 3:
    neednum();
age = input("Are you an adult or child? (A/C): ");
sex = input("What sex are you? (M/F): ");

age = age.lower();
sex = sex.lower();

if age == "a":
    age = 1;
elif age == "c":
    age = 0;

if sex == "m":
    sex = 1;
elif sex == "f":
    sex = 0;

final = [[cnum, age, sex]];
print(final);
check1 = 0;
check2 = 0;
check3 = 0;
check4 = 0;
check5 = 0;
check6 = 0;
check7 = 0;
check8 = 0;
check9 = 0;
check10 = 0;

inp = input("How many random samples would you like? ");
inp4 = input("Show slice info? (Not recommended for large tests): ");
inp4 = inp4.lower();
inp5 = input("Risk crash? (Y/N): ");
inp6 = input("Show instant results?: ");
inp5 = inp5.lower();
inp6 = inp6.lower();
if inp4 == "yes" or inp4 == "yeah" or inp4 == "yep" or inp4 == "y":
    inp4 = "y";
if inp6 == "yes" or inp6 == "yeah" or inp6 == "yep" or inp6 == "y":
    inp6 = "y";
inp2 = int(inp);

sSizes = [];
iterator = 0;

treeList = [];
nearList = [];
forestList = [];
uList = [];

hour = 0;
hours = 0;
minute = 0;
minutes = 0;
seconds = 0;

start_time1 = time.time();#Time to make some efficiency calculations
while iterator < inp2:
    samp = np.random.rand();
    sSizes.append(samp);
    iterator+=1;
print("%s seconds to generate slices." % (time.time() - start_time1));

start_time2 = time.time();#Give user view of how long things are gonna take from a rough sample of generating 10%
start_time3 = time.time();#Metric to measure by

def timing(stime):#ETA Calc (old)
    print((a/len(sSizes)))
    try:
        hour = int((time.time()-stime)/(a/len(sSizes))-(time.time()-stime))/60/60;
    except:
        hour = 0;
    hours = int(hour)
    try:
        minute = int((time.time()-stime)/(a/len(sSizes))-(time.time()-stime))/60;
    except:
        minute = 0;
    minutes = int(minute);
    while minutes > 59:
        minutes = minutes-60;
    seconds = int((time.time()-stime)/(a/len(sSizes))-(time.time()-stime))%60;
    if hours == 1 and minutes > 1:
        print("ETA", hours, "hour,", minutes, "minutes and", seconds, "seconds to completion at current rate.");
    elif minutes == 1 and hours > 1:
        print("ETA", hours, "hours,", minutes, "minute and", seconds, "seconds to completion at current rate.");
    elif hours == 1 and minutes == 1:
        print("ETA", hour, "hour,", minute, "minute and", seconds, "seconds to completion at current rate.");
    else:
        print("ETA", hours, "hours,", minutes, "minutes and", seconds, "seconds to completion at current rate.");
    print();

#Loading bar equipment
d = 0;
e = 100;
bar = "¶";
blank = "¶";

st4 = time.time();

for a in range(len(sSizes)):
    if inp5 == "y":
        b = float(a/len(sSizes)*100);
        c = str(b)+"%";
        perc = c+" done.";
        if int(b) != d:
            d = int(b);
            e-=1;
        physbar = "¶"+str(bar*d)+str(blank*e)+"¶";
        print("\r", physbar, perc, end = "");
    else:
        if a/len(sSizes)*100 > 1.00 and check1 == 0:
            print("1% done");
            timing(start_time3);
            check1 = 1;
        elif a/len(sSizes)*100 > 10.00 and check2 == 0:
            print("10% done");
            print("%s seconds to process 10 percent." % (int(time.time() - start_time2)));
            timing(start_time3);
            start_time2 = time.time();
            check2 = 1;
        elif a/len(sSizes)*100 > 20.00 and check3 == 0:
            print("20% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            timing(start_time3);
            start_time2 = time.time();
            check3 = 1;
        elif a/len(sSizes)*100 > 30.00 and check4 == 0:
            print("30% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            timing(start_time3);
            start_time2 = time.time();
            check4 = 1;
        elif a/len(sSizes)*100 > 40.00 and check5 == 0:
            print("40% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            start_time2 = time.time();
            timing(start_time3);
            check5 = 1;
        elif a/len(sSizes)*100 > 50.00 and check6 == 0:
            print("50% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            start_time2 = time.time();
            check6 = 1;
            timing(start_time3);
        elif a/len(sSizes)*100 > 60.00 and check7 == 0:
            print("60% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            start_time2 = time.time();
            check7 = 1;
            timing(start_time3);
        elif a/len(sSizes)*100 > 70.00 and check8 == 0:
            print("70% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            start_time2 = time.time();
            check8 = 1;
            timing(start_time3);
        elif a/len(sSizes)*100 > 80.00 and check9 == 0:
            print("80% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            start_time2 = time.time();
            check9 = 1;
            timing(start_time3);
        elif a/len(sSizes)*100 > 90.00 and check10 == 0:
            print("90% done");
            print("%s seconds to process another 10 percent." % (int(time.time() - start_time2)));
            start_time2 = time.time();
            check10 = 1;
            timing(start_time3);
    if inp4 == "y":
        print("Entry", a+1, "has a sample partition of:", sSizes[a]);
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = sSizes[a]);
    
    try:
        tree_classifier = tree.DecisionTreeClassifier();
        tree_classifier = tree_classifier.fit(X_train, y_train);
        tree_predictions = tree_classifier.predict(final);
    except:
        if inp6 == "y":
            print("Bad data at sample", a+1,"with slice value of:", sSizes[a],"for Tree method");
    try:
        knn_classifier = neighbors.KNeighborsClassifier();
        knn_classifier = knn_classifier.fit(X_train, y_train);
        knn_predictions = knn_classifier.predict(final);
    except:
        if inp6 == "y":
            print("Bad data at sample", a+1,"with slice value of:", sSizes[a],"for Neighbor method");
        
    try:
        rf_classifier = ensemble.RandomForestClassifier();
        rf_classifier = rf_classifier.fit(X_train, y_train);
        rf_predictions = rf_classifier.predict(final);
    except:
        if inp6 == "y":
            print("Bad data at sample", a+1,"with slice value of:", sSizes[a],"for Forest method");
    
    if inp6 == "y":
        print("Tree:",tree_predictions);
        print("Nearest:", knn_predictions);
        print("Forest:", rf_predictions);
    
    treeList.append(tree_predictions);
    nearList.append(knn_predictions);
    forestList.append(rf_predictions);
print();
print("Finished in %s seconds." % (int(time.time()-start_time3)));
print("Tree avg % chance of survival:",np.mean(treeList)*100);
print("Nearest avg % chance of survival:",np.mean(nearList)*100);
print("Forest avg % chance of survival:",np.mean(forestList)*100);

<h3> Question 3 Answer:</h3>

To find which feature was the most important in determining whether a person on the Titanic lived or not, I iterated through many combinations of features to find trends.

Here are the combinations I tried:

Variations going through:

    0, A, M -- Forest = 0.0
    3, A, M -- Forest = 0.2
    2, A, M -- Forest = 0.4
    1, A, M -- Forest = 2.8
    
    0, A, F -- Forest = 96.8
    3, A, F -- Forest = 19.2
    2, A, F -- Forest = 99.4
    1, A, F -- Forest = 99.6
    
    0, C, M -- Forest = 87.8
    3, C, M -- Forest = 3.4
    2, C, M -- Forest = 95.0
    1, C, M -- Forest = 97.2
    
    0, C, F -- Forest = 99.0
    3, C, F -- Forest = 28.2
    2, C, F -- Forest = 98.6
    1, C, F -- Forest = 99.2
    
    *A = Adult
    *C = Child
    *M = Male
    *F = Female
    *0-3 = Classes
    
For all of these, I used 500 samples to get accurate scores that would not take longer than 10 seconds to load each time. This amount of samples gets my number down to the nearest .2, which is helpful in making it more accurate while still being reasonable in load time. 

<u>Here are some of my conclusions from testing all these combinations. </u>
    
Class - This feature mattered mostly whether the person was in 3rd class or not. Besides 3rd class, females of all ages and male children were likely to live. Males of all classes were extremely likely to die, but 1st class men had a slight chance of living. 

Gender - In adults, gender made an extreme difference. Adult females are very likely to live (besides third class), whereas males were highly likely to die. In children, gender did not make as much of a difference. Boys were only slightly less likely to live than girls. It was consistent overall that females were more likely to live than males. 

Age - In females, the likelihood of surviving was about the same regardless of age. The only slight difference in female adults vs. female children was that female adults in higher classes were slightly more likely to survive, and female children in working/lower classes were more likely to survive. As for males, being a child vs. adult made a huge difference. Male children were likely to live and male adults were highly likely to die. Among all ages and gender combinations, being third class meant you were likely to die. 
    
Each of these features made a significant difference in determining who lived or died. I believe the least important feature of the three was Class, because all but one tended to be likely to live. First and second class tended to be almost the same, with the workers on the Titanic right behind them, and third class people usually died. <b>I think the most important feature was Gender. </b> Among all classes and ages, gender made a difference. Though this difference was smaller in childen overall, what pushed me to say gender over age is that a working female child had a 99.0% chance of living, whereas a working male child had a 87.8% chance of living, and in third class a female child had a 28.2% chance of living, whereas a male child in third class had a 3.4% chance of living. This is still a big difference, even thought it's not as extreme as the difference between the survivial rates of male and female adults. Age was a close second in how much it influenced the outcome. 


 <h3> Conclusion </h3>
 
In this project, I learned about how to test the accuracy of machine learning algorithms, as well as how to use them to get useful results from a set of data. It is interesting how a computer is able to figure out patterns and can use this to get results when given parameters about a dataset, without me ever directly telling it the patterns. I felt that this was proven when the results of the patterns I discovered when testing different combinations of features matched the results I got for the three imaginary people I predicted would survive or die on the Titanic. The third class adult male died, and the first class adult and child females survived.

I still have yet to grasp a better understanding of what these algorithms we use are like. By just calling them in the code, I do not actually see the math that goes on. I am curious about what the algorithm actually consists of mathematically. 

There are some aspects about the data that I think could have messed with my results a little bit. For example, I am concerned about how reasonable the results were for the children who worked on the titanic. There were no young children who worked on the titanic, but there were some teenagers. This also makes me wonder -- what was considered the cut-off age for children and adults in this data? This would affect the results for the surivial rates of the workers, as well as how age affected the outcome. 